### PR TITLE
Import future annotations for pytest 6, Python 3.9 compatibility

### LINKED ISSUE #755: Broken compatibility with pytest<7 (pytest.Parser type annotation)
The parser annotation in plugin.py introduced in 10.0 does not work with pytest 6. https://github.com/pytest-dev/pytest-testinfra/blob/dc48cd98f3b1970ecbad63f866a94f8283b79ce4/testinfra/plugin.py#L40
`pytest.Parser` is only available from pytest 7.0.0
```
>>> from testinfra import plugin
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/testinfra/plugin.py", line 40, in <module>
    def pytest_addoption(parser: pytest.Parser) -> None:
AttributeError: module 'pytest' has no attribute 'Parser'
```

While specifying minimal pytest version would be a solution, I would rather recommend finding another solution, as RHEL-9/Alma Linux 9/CentOS Stream 9 are running pytest 6 (and Python 3.9).

I'd be happy to help with finding a solution, should you decide to keep pytest 6 compatibility.

### PR DESCRIPTION
**Pull request by martinhoyer**
Makes testinfra v10.0.0 work with Python 3.9 and pytest 6.2.2, which is being used in CentOS-Stream-9-based distributions.
 
Resolves #755.

### CODE REVIEW

**Comment by martinhoyer** [comment]
I've successfully ran tests on RHEL-9 (Python 3.9) with install_requires `pytest==6.0.0`.
When changed to `pytest<6`, py tests failed with INTERNALERRORs. Adding therefore a `pytest>=6` requirement to the setup.cfg.

**Review by philpep — APPROVED** [review]

**Comment by philpep** [comment]
Sounds reasonable, merged, thanks for this!
